spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/prompthub}
    username: ${DATABASE_USERNAME:spring}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
  jpa:
    hibernate:
      ddl-auto: validate  # 운영에서는 스키마 변경 금지
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.griotold.prompthub: INFO
    root: INFO