name: Run Test
on:
  push:
    branches-ignore: [ master ]  # master 제외하고 모든 브랜치에서 테스트
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Java 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3️⃣ 테스트 실행
      - name: Run All Tests
        run: |
          chmod +x ./gradlew
          ./gradlew clean test